### ISSUE TITLE
[Bug] In ready.js bot.endGiveaway is not a function

### ISSUE THREAD

**Issue by KingDGrizzle** [GilbertGobbels/GAwesomeBot#103]
[Here](http://i.kingdgrizzle.tk/2017/03/m0E8g8.png) is what I'm talking about.

Is doing a 
```js
let Giveaways = require("./../Modules/Giveaways.js");

Giveaways.end();
```
the correct way, or do we have to change it? @HilbertGilbertson I told ya I'ma throw something at you

**Comment by JjTheHusky** [comment]
Bumping.
I just tested this and can confirm. (and the bot is now in a "boot crash")
It appears this happens when a giveaway tries to end, no matter the situation. The only fix is to get into the database and set "giveaway going on" to false.
I thought this would only occur if the bot were to be off when the giveaway timer is up, but it did it when it ended.

**Comment by theanidox** [comment]
Could `Giveaways.end()` (or something else) set the database when a giveaway ends?

**Comment by JjTheHusky** [comment]
Bumping again, my bot token reset after 1000 logins, all from this issue, please fix this asap.
`0|bot      | TypeError: bot.endGiveaway is not a function
0|bot      |     at Timeout.setTimeout [as _onTimeout] (/root/HuskyBot/Events/re                                                                                                                                                                                                                                             ady.js:134:15)
0|bot      |     at ontimeout (timers.js:386:14)
0|bot      |     at tryOnTimeout (timers.js:250:5)
0|bot      |     at Timer.listOnTimeout (timers.js:214:5)
0|bot      | TypeError: bot.endGiveaway is not a function
0|bot      |     at Timeout.setTimeout [as _onTimeout] (/root/HuskyBot/Events/re                                                                                                                                                                                                                                             ady.js:134:15)
0|bot      |     at ontimeout (timers.js:386:14)
0|bot      |     at tryOnTimeout (timers.js:250:5)
0|bot      |     at Timer.listOnTimeout (timers.js:214:5)
0|bot      | TypeError: bot.endGiveaway is not a function
0|bot      |     at Timeout.setTimeout [as _onTimeout] (/root/HuskyBot/Events/re                                                                                                                                                                                                                                             ady.js:134:15)
0|bot      |     at ontimeout (timers.js:386:14)
0|bot      |     at tryOnTimeout (timers.js:250:5)
0|bot      |     at Timer.listOnTimeout (timers.js:214:5)
`

**Comment by TTtie** [comment]
>crashing

```js
process.on("uncaughtException", console.error)
```

or try-catch, where are ya

**Comment by TTtie** [comment]
Also heh, bot.endGiveaway isn't even defined at Platform/Discord.js

**Comment by KingDGrizzle** [comment]
You'd think we are smart but no. I broke lotteries due to "bot is not defined", I fix lotteries

**Comment by TTtie** [comment]
Is it this? https://github.com/GilbertGobbels/GAwesomeBot/blob/development/Events/ready.js#L134

**Comment by TishGithub** [comment]
Same
I get this `tish@rpi:~/Desktop/GAwesomeBot$ node bot --production
info: Started bot application
info: Shards: 1
info: Shard 1/1 connected: 1 guilds, 12 users
info: All shards connected
info: Started the best Discord bot, version 4.0.1
     _                                         ____        _   
    / \__      _____  ___  ___  _ __ ___   ___| __ )  ___ | |_ 
   / _ \ \ /\ / / _ \/ __|/ _ \| '_ ` _ \ / _ \  _ \ / _ \| __|
  / ___ \ V  V /  __/\__ \ (_) | | | | | |  __/ |_) | (_) | |_ 
 /_/   \_\_/\_/ \___||___/\___/|_| |_| |_|\___|____/ \___/ \__|

info: Opened http web interface on 127.0.0.1:8080
/home/tish/Desktop/GAwesomeBot/Events/ready.js:134
                                        bot.endGiveaway(svr, serverDocument, ch, channelDocument);
                                            ^

TypeError: bot.endGiveaway is not a function
    at Timeout.setTimeout [as _onTimeout] (/home/tish/Desktop/GAwesomeBot/Events/ready.js:134:15)
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)`

**Comment by TTtie** [comment]
I think `bot.endGiveaway` should be :100: defined

**Comment by vladfrangu** [comment]
I mark this issue / pull request as closed. If you have anything against this, ping me.

_This is an semi-automated reply using the Saved Replies function_

## Why did I take this decision?

This issue has been fixed in indev.
