### ISSUE TITLE
Website on bot crashes. 

### ISSUE THREAD

**Issue by Testdude3234** [GilbertGobbels/GAwesomeBot#140]
I tried a few solutions and have not solved it yet.. Are there any more solutions?

TypeError: Cannot read property 'unmask' of undefined
    at Receiver.unmask (/home/aidenjay345/dogbot2/GAwesomeBot/node_modules/engine.io/node_modules/ws/lib/Receiver.js:306:46)
    at Receiver.finish (/home/aidenjay345/dogbot2/GAwesomeBot/node_modules/engine.io/node_modules/ws/lib/Receiver.js:505:25)
    at Receiver.expectHandler (/home/aidenjay345/dogbot2/GAwesomeBot/node_modules/engine.io/node_modules/ws/lib/Receiver.js:493:33)
    at Receiver.add (/home/aidenjay345/dogbot2/GAwesomeBot/node_modules/engine.io/node_modules/ws/lib/Receiver.js:103:24)
    at Socket.realHandler (/home/aidenjay345/dogbot2/GAwesomeBot/node_modules/engine.io/node_modules/ws/lib/WebSocket.js:825:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)

**Comment by KingDGrizzle** [comment]
Will be fixed soon, after the new package.json will be finished

**Comment by Testdude3234** [comment]
Alright thanks, is there a ETA yet? or unknown

**Comment by KingDGrizzle** [comment]
Does soon™️ work? But for real, its planned. Should come next month at the very most!

**Comment by Testdude3234** [comment]
Alright thanks!
