### ISSUE TITLE
[Issue] Giveaway can't end properly

### ISSUE THREAD

**Issue by JjTheHusky** [GilbertGobbels/GAwesomeBot#154]
I tried to run a giveaway, while the commands worked, the bot never announced the winner, and when I typed lottery, it said the winner will be announced: "18 hours ago."

I go to the dashboard and try to manually end the giveaway, but it crashes the bot, giving a "Bot not defined" error. It did, however, end the giveaway, not announcing the winner. Logs below.

Now I didn't have the logs of when the giveaway should have ended but I suspect it gave the same error and crashed.
` info: Treating '&lottery start' as a command svrid=2774990109887692                                                                                                                                                             80, chid=295370522898989057, usrid=99292263909195776
 info: Treating '&lottery start' as a command svrid=277499010988769280, chid=295370522898989057, usrid=99292263909195776
 info: Treating '&lottery join' as a command svrid=277499010988769280, chid=295370522898989057, usrid=134644062828494848
 info: Treating '&lottery enroll' as a command svrid=277499010988769280, chid=295370522898989057, usrid=99292263909195776
 ReferenceError: bot is not defined
     at db.users.findOrCreate (/root/HuskyBot/Modules/Lotteries.js:44:43)
    at /root/HuskyBot/node_modules/mongoose-findorcreate/index.js:31:11
     at model.Query.<anonymous> (/root/HuskyBot/node_modules/mongoose/lib/model.js:3737:16)
     at /root/HuskyBot/node_modules/kareem/index.js:277:21
     at /root/HuskyBot/node_modules/kareem/index.js:131:16
     at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
 info: Started bot application
`
Sorry I forgot to hastebin ;P

Maybe we should just remake the giveaway command, seeing how it has a lot of issues. We could also put how long it can be instead of it being just an hour.

**Comment by KingDGrizzle** [comment]
I thought @hilberthilbertson fixed it.. we'll see about it

**Comment by vladfrangu** [comment]
I mark this pull request as merge-ready. If you have anything against me merging it, please ping me.

_This is an automated reply using the Saved Replies function_

## Why did I take this decision?

Ok, probably not fixed yet, but it will be fixed. Check indev for the commit (whenever that will happen).
I'll make another comment here when its done, closing this issue with it

**Comment by vladfrangu** [comment]
lmfao, I used the wrong auto reply. Closing as its technically fixed
