### ISSUE TITLE
Update page is broken

### ISSUE THREAD

**Issue by TTtie** [GilbertGobbels/GAwesomeBot#173]
Might also be by using old config.
This is the error thrown:

```
ReferenceError: C:\Users\user\Documents\Nová složka\gawesomebot\Web\views\pages\maintainer-version.ejs:6
    4| 	<title><%= serverData.name %> Maintainer Console</title>

    5| 	<% include ../partials/head %>

 >> 6| 	<% if (!utd && !disabled) { %>

    7| 	<link rel="stylesheet" href="/static/css/codemirror.css">

    8| 	<link rel="stylesheet" href="/static/css/codemirror-monokai.css">

    9| 	<script src="/static/js/codemirror.js"></script>


utd is not defined
    at eval (eval at compile (C:\Users\user\Documents\Nová složka\gawesomebot\node_modules\ejs\lib\ejs.js:524:12), <anonymous>:27:8)
    at returnedFn (C:\Users\user\Documents\Nová složka\gawesomebot\node_modules\ejs\lib\ejs.js:555:17)
    at tryHandleCache (C:\Users\user\Documents\Nová složka\gawesomebot\node_modules\ejs\lib\ejs.js:203:34)
    at View.exports.renderFile [as engine] (C:\Users\user\Documents\Nová složka\gawesomebot\node_modules\ejs\lib\ejs.js:412:10)
    at View.render (C:\Users\user\Documents\Nová složka\gawesomebot\node_modules\express\lib\view.js:128:8)
    at tryRender (C:\Users\user\Documents\Nová složka\gawesomebot\node_modules\express\lib\application.js:640:10)
    at Function.render (C:\Users\user\Documents\Nová složka\gawesomebot\node_modules\express\lib\application.js:592:3)
    at ServerResponse.render (C:\Users\user\Documents\Nová složka\gawesomebot\node_modules\express\lib\response.js:971:7)
    at Updater.check.version (C:\Users\user\Documents\Nová složka\gawesomebot\Web\WebServer.js:3635:10)
    at unirest.get.end.result (C:\Users\user\Documents\Nová složka\gawesomebot\Modules\Updater.js:10:9)
    at Request.handleRequestResponse [as _callback] (C:\Users\user\Documents\Nová složka\gawesomebot\node_modules\unirest\index.js:463:26)
    at Request.self.callback (C:\Users\user\Documents\Nová složka\gawesomebot\node_modules\unirest\node_modules\request\request.js:187:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (C:\Users\user\Documents\Nová složka\gawesomebot\node_modules\unirest\node_modules\request\request.js:1044:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (C:\Users\user\Documents\Nová složka\gawesomebot\node_modules\unirest\node_modules\request\request.js:965:12)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickDomainCallback (internal/process/next_tick.js:198:9)```

**Comment by JjTheHusky** [comment]
One, please make sure to have this line in the config file, this line is located right under the version number line
`    "branch": "experimental",`

Secondly, this happens when the update server is not online, in which @GilbertGobbels hosts.

**Comment by TTtie** [comment]
I forgot to clone the dev branch aaaa

**Comment by GilbertGobbels** [comment]
Husky explained perfectly
