### ISSUE TITLE
Website crashing the bot

### ISSUE THREAD

**Issue by MayhemBill** [GilbertGobbels/GAwesomeBot#203]
I click on Ongoing Activities, and the site/bot crash.
Log as follows:

info: Opened https web interface on 0.0.0.0:443
info: Opened http web interface on 0.0.0.0:80
events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'name' of undefined
    at checkAuth (/home/division25/drive2/bots/gawesome/Web/WebServer.js:3311:40)
    at db.servers.findOne (/home/division25/drive2/bots/gawesome/Web/WebServer.js:720:10)
    at Query.<anonymous> (/home/division25/drive2/bots/gawesome/node_modules/mongoose/lib/model.js:4054:16)
    at /home/division25/drive2/bots/gawesome/node_modules/kareem/index.js:273:21
    at /home/division25/drive2/bots/gawesome/node_modules/kareem/index.js:131:16
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)

**Comment by Gilbert142** [comment]
On what version and on what branch does this error occur?

**Comment by MayhemBill** [comment]
it's 4.0.1 and it's the master branch

**Comment by wasdennnoch** [comment]
Pretty sure that was fixed in the rewrite already.

**Comment by Gilbert142** [comment]
This Bug has been fixed in indev-4.0.2, it will be merged into the stable/experimental branches soon!
