### ISSUE TITLE
[Bug] Ongoing activites

### ISSUE THREAD

**Issue by ItsLachy** [GilbertGobbels/GAwesomeBot#22]
URL: https://bot.lachy.io/dashboard/other/ongoing-activities?svrid=****************
**Error**
`TypeError: /root/GAwesomeBot/Web/views/pages/admin-ongoing-activities.ejs:66
   64| <div class="card-content">
   65| <h3 class="title is-3 has-text-centered">
 66| <%= trivia[i].set.charAt(0) + trivia[i].set.slice(1)
   67| </h3>
   68| <div class="level is-mobile">
   69| <div class="level-item has-text-centered">

trivia[i].set.charAt is not a function
   at eval (eval at <anonymous> (/root/GAwesomeBot/node_modules/ejs/lib/ejs.js:481:12), <anonymous>:538:38)
   at returnedFn (/root/GAwesomeBot/node_modules/ejs/lib/ejs.js:512:17)
   at View.exports.renderFile [as engine] (/root/GAwesomeBot/node_modules/ejs/lib/ejs.js:364:31)
   at View.render (/root/GAwesomeBot/node_modules/express/lib/view.js:126:8)
   at tryRender (/root/GAwesomeBot/node_modules/express/lib/application.js:639:10)
   at EventEmitter.render (/root/GAwesomeBot/node_modules/express/lib/application.js:591:3)
   at ServerResponse.render (/root/GAwesomeBot/node_modules/express/lib/response.js:960:7)
   at checkAuth (/root/GAwesomeBot/Web/WebServer.js:3333:8)
   at db.servers.findOne (/root/GAwesomeBot/Web/WebServer.js:683:10)
   at Query.<anonymous> (/root/GAwesomeBot/node_modules/mongoose/lib/model.js:3419:16)
   at /root/GAwesomeBot/node_modules/kareem/index.js:264:21
   at /root/GAwesomeBot/node_modules/kareem/index.js:127:16
   at _combinedTickCallback (internal/process/next_tick.js:67:7)
   at process._tickDomainCallback (internal/process/next_tick.js:122:9)`

**Comment by KingDGrizzle** [comment]
What bot version are you running? The master branch or the development on

**Comment by KingDGrizzle** [comment]
Works just fine for me on the development branch. If its about your issue with MongoDB, well, you got that solved 😛

**Comment by KingDGrizzle** [comment]
Ignore me, this is still borked: http://pastebin.com/3PdZk2rG

**Comment by HilbertGilbertson** [comment]
Can anyone provide steps to reproduce?

**Comment by KingDGrizzle** [comment]
Start a trivia game
Go to Admin Panel, Ongoing activities

**Comment by ItsLachy** [comment]
Can confirm.

**Comment by HilbertGilbertson** [comment]
Fixed in #50.

**Comment by HilbertGilbertson** [comment]
Fixed in #56.
